### ISSUE TITLE
Can't go through proxy

### ISSUE THREAD

**Issue by ctapang** [tomayac/adwords-reports-nodejs-lib#1]
This adwords library uses the node js https library. I have modified it to use the newer npm request module instead. I think it works better. Let me know if you want/need this revised version, and I can submit a PR.

**Comment by tomayac** [comment]
Hi @ctapang, 

Sorry for the late reply, I was OoO. Thanks very much for the announced Pull Request, please do send it over and I am happy to merge it in. I am closing the issue pro-actively now, as we will continue the discussion on the upcoming Pull Request thread. 

Thanks,
Tom

**Comment by tomayac** [comment]
@ctapang Friendly ping :-)

**Comment by ctapang** [comment]
Havent finalized it as yet. May have to add a new method to keep original API intact.

Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Thomas Steiner notifications@github.com Date: 9/2/16  6:50 AM  (GMT-08:00) To: tomayac/adwords-reports-nodejs-lib adwords-reports-nodejs-lib@noreply.github.com Cc: ctapang ctapang@hotmail.com, Mention mention@noreply.github.com Subject: Re: [tomayac/adwords-reports-nodejs-lib] Can't go through proxy (#1) 
@ctapang Friendly ping :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tomayac/adwords-reports-nodejs-lib","title":"tomayac/adwords-reports-nodejs-lib","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tomayac/adwords-reports-nodejs-lib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tomayac in #1: @ctapang Friendly ping :-)"}],"action":{"name":"View Issue","url":"https://github.com/tomayac/adwords-reports-nodejs-lib/issues/1#issuecomment-244380125"}}}
