### ISSUE TITLE
Get back a binary response

### ISSUE THREAD

**Issue by benburkhart1** [tomayac/adwords-reports-nodejs-lib#3]
When I do a simple query, I'm getting back a binary response.

```
        var adwords = require('adwords-reports-nodejs-lib');
        adwords.getReport({
                // Change to a real Customer ID.
                cid: customer_id,
                // Change AWQL query according to the grammar published at
                // https://developers.google.com/adwords/api/docs/guides/awql.
                //
                // Check https://developers.google.com/adwords/api/docs/appendix/reports/all-reports
                // for the available report types and fields.
                awql: 'SELECT Cost,Name FROM CAMPAIGN_PERFORMANCE_REPORT DURING LAST_WEEK'
        }).then(function(data) {
                console.log(data);
        }).catch(function(err) {
                throw(err);
        });
```

data in the .then() function is binary data. What am I doing wrong here?

**Comment by tomayac** [comment]
Seems like you have an error in your AWQL query: `Name` is not supported by the [Campaign Performance Report](https://developers.google.com/adwords/api/docs/appendix/reports/campaign-performance-report). Does it work if you fix the query so that instead of `Name` you use `CampaignName` (see [here](https://developers.google.com/adwords/api/docs/appendix/reports/campaign-performance-report#campaignname))?

**Comment by benburkhart1** [comment]
I still get the issue even omitting Name completely (or having it properly as CampaignName). I do not see where you're actually handling the zlib you're requesting. I am using Node v5.8.0 for reference.

**Comment by benburkhart1** [comment]
It appears like the zlib stuff was not handled. I opened a PR, not necessarily ready-to-merge, but this fixes the issue I'm seeing, and I'm not sure how it could be working without it.

https://github.com/tomayac/adwords-reports-nodejs-lib/pull/4

**Comment by beam-tech** [comment]
I have the same problem. What structure should return to 'data'? My app output: �̟2l�J�:d�b9�3�s�*i�B�z�Xq�ɥ���DHOZ�&׷�o�䢁�2Z?�O�&K�b�y�I*<�ܑ�k������I�
                                                                                 ���+��/۲^��

**Comment by tomayac** [comment]
Sorry for the radio silence. I will look into the issue tomorrow and come back with a fix. Thanks for your patience!

**Comment by benburkhart1** [comment]
A fix has been here for awhile

https://github.com/tomayac/adwords-reports-nodejs-lib/pull/4

**Comment by tomayac** [comment]
Yepp, need to review and merge it. As I said, sorry for the radio silence :-/ And thanks for caring!
